routes/web.php
<?php

use App\Http\Controllers\FrontEnd\BoothController;
use App\Http\Controllers\FrontEnd\ClassroomController;
use App\Http\Controllers\FrontEnd\InvoiceController;
use App\Http\Controllers\FrontEnd\LandingController;
use App\Http\Controllers\FrontEnd\LobbyController;
use App\Http\Controllers\FrontEnd\MainStageController;
use App\Http\Controllers\FrontEnd\NotificationController;
use App\Http\Controllers\FrontEnd\ProfileController;
use App\Http\Controllers\FrontEnd\ScheduleController;
use App\Http\Middleware\CheckSession;
use App\Http\Middleware\CheckUserStatus;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'middleware' => [CheckSession::class, CheckUserStatus::class],
], function () {
    Route::get('/', [LandingController::class, 'index'])->withoutMiddleware([CheckSession::class, CheckUserStatus::class]);

    Route::post('/profile', [ProfileController::class, 'update']);

    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications', [NotificationController::class, 'update']);

    Route::get('/home', [LobbyController::class, 'home']);

    Route::get('/download-qr/{qr}', [LobbyController::class, 'downloadQr']);

    Route::get('/mainstage', [MainStageController::class, 'index']);

    Route::get('/classroom', [ClassroomController::class, 'index']);

    Route::get('/schedule-list', [ScheduleController::class, 'index']);
    Route::post('/schedule-find', [ScheduleController::class, 'show']);
    Route::post('/schedule-send-message', [ScheduleController::class, 'sendMessage']);

    Route::get('/booth', [BoothController::class, 'index']);
    Route::get('/booth-list', [BoothController::class, 'boothList']);
    Route::post('/booth-find', [BoothController::class, 'boothFind']);
    Route::get('/booth/detail', [BoothController::class, 'show']);

    Route::post('/count-visitor', function () {
        return 0;
    });

    //Invoice
    Route::get('/invoice', [InvoiceController::class, 'index']);
});

Route::get('/scannerapp', function () {
    return redirect(config('eventy.scanner_link'));
});


Route::get('/email', function () {
    $participant = \App\Models\Participant::find(64);

    $mail['event_logo'] = preferGet('logo_events');
    $mail['name'] = $participant->name;
    $mail['email'] = $participant->email;

//    $participant->sendEmailRegistration($mail);

    return view('web.Email.reminder', $mail);
});

app/Models/Doorprize.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Doorprize extends Model
{
    use HasFactory, SoftDeletes;

    public function getParticipantsAttribute()
    {
        if ($this->doorprize_type === 'Doorprize 1') {
            return $this->hasMany(Participant::class, 'doorprize_id', 'id')->latest('is_pickup_doorprize')->get();
        }

        if ($this->doorprize_type === 'Doorprize 2') {
            return $this->hasMany(Participant::class, 'doorprize2_id', 'id')->latest('is_pickup_doorprize2')->get();
        }

        return $this->hasMany(Participant::class, 'doorprize3_id', 'id')->latest('is_pickup_doorprize3')->get();
    }

    public function getParticipantsLeftAttribute()
    {
        if ($this->doorprize_type === 'Doorprize 1') {
            return $this->hasMany(Participant::class, 'doorprize_id', 'id')->where('is_pickup_doorprize', 0)->get();
        }

        if ($this->doorprize_type === 'Doorprize 2') {
            return $this->hasMany(Participant::class, 'doorprize2_id', 'id')->where('is_pickup_doorprize2', 0)->get();
        }

        return $this->hasMany(Participant::class, 'doorprize3_id', 'id')->where('is_pickup_doorprize3', 0)->get();
    }

    public function getPresentImageAttribute()
    {
        if ($this->image) {
            return getS3EndpointFile($this->image);
        }

        return '';
    }

    public function getPresentNameAttribute()
    {
        $day = date('d', strtotime($this->available_at));
        $name = 'Day Test: ';
        if ($day == '24') {
            $name = 'Day 1: ';
        } else if ($day == '25') {
            $name = 'Day 2: ';
        }

        return $name . $this->name;
    }

    public function getPresentCountdownAttribute()
    {
        return strtotime(date('Y-m-d H:i:s', strtotime("+{$this->minutes} minutes", strtotime($this->draw_at)))) - time();
    }

    public function getIsPickupDoorprizeAttribute()
    {
        if ($this->doorprize_type === 'Doorprize 1') {
            return $this->hasMany(Participant::class, 'doorprize_id', 'id')->where('is_pickup_doorprize', 1)->count();
        }

        if ($this->doorprize_type === 'Doorprize 2') {
            return $this->hasMany(Participant::class, 'doorprize2_id', 'id')->where('is_pickup_doorprize2', 1)->count();
        }

        return $this->hasMany(Participant::class, 'doorprize3_id', 'id')->where('is_pickup_doorprize3', 1)->count();
    }

    public function getIsLeftAttribute()
    {
        return $this->quantity - $this->is_pickup_doorprize;
    }
}

resources/views/admin/Doorprize/draw.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Doorprize Items</title>
    <link rel="shortcut icon" href="{{ preferGet('icon_events') }}">
    <link rel="stylesheet" href="{{ asset('packages/bootstrap5/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('packages/swiper/swiper-bundle.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/admin/Doorprize/doorprize.css') . '?v=' . date('YmdH') }}">
    <style>
        .custom-doorprize-item__title {
            white-space: normal;
            width: 80%;
            font-size: 12px;
        }
        @media (min-width: 1400px) {
            .custom-doorprize-item__title {
                font-size: 14px;
            }
        }
        @media (min-width: 1900px) {
            .custom-doorprize-item__title {
                font-size: 20px;
            }
        }
        .row-scroll {
            max-height: 395px;
            overflow-x: auto;
        }
        @media (min-width: 1400px) {
            .row-scroll {
                max-height: 405px;
            }
        }
        @media (min-width: 1600px) {
            .row-scroll {
                max-height: 405px;
            }
        }
        @media (min-width: 1900px) {
            .row-scroll {
                max-height: 620px;
            }
        }
        .row-scroll::-webkit-scrollbar {
            width: 5px;
        }
        .row-scroll::-webkit-scrollbar-track {
            background: #DADADA;
            border-radius: 15px;
        }
        .row-scroll::-webkit-scrollbar-thumb {
            background: #B2B2B2;
            border-radius: 15px;
        }
        .row-scroll::-webkit-scrollbar-thumb:hover {
            background: #999999;
        }
    </style>
</head>
<body>

<div class="container container-custom">
    <div class="row">
        <div class="col-lg-12">
            <div class="img-group">
                <img src="{{ asset('images/doorprize/img_logo_event@2x.png') }}" alt="" class="img-center img-fluid" style="max-width: 15%; height: auto;">
            </div>

            <div class="text-center">
                <h1 class="doorprize-title border-white fs-3 mb-4">SELECT DOORPRIZE ITEMS</h1>
            </div>
        </div>
    </div>
    <div class="row position-relative justify-content-center">
        <div class="col-lg-8">
            <div class="row row-scroll">
                @foreach($doorprizes as $doorprize)
                    <div class="col-lg-4">
                        <a href="{{ \crocodicstudio\crudbooster\helpers\CRUDBooster::mainpath('button?id=' . $doorprize->id) }}" class="custom-doorprize-item">
                            @if(dateTime() < $doorprize->available_at)
                                <img src="{{ asset('images/doorprize/item_box_nextdraw.svg') }}" alt="" class="w-100">
                                <h3 class="custom-doorprize-item__title" style="color: #041423;">
                                    @if($doorprize->draw_type === 'General')
                                        <span class="d-inline-block mb-2">{{ $doorprize->present_name }}</span> <br> <span>(Next Draw)</span>
                                    @else
                                        <span class="d-inline-block mb-2">{{ $doorprize->present_name }}</span> <br> <span>(Grand Prize)</span>
                                    @endif
                                </h3>
                            @else
                                @if($doorprize->is_drawn)
                                    <img src="{{ asset('images/doorprize/item_box_generated.svg') }}" alt="" class="w-100">
                                    <h3 class="custom-doorprize-item__title text-white">
                                        <span class="d-inline-block mb-2">{{ $doorprize->present_name }}</span> <br> <span>(Done)</span>
                                    </h3>
                                @else
                                    <img src="{{ asset('images/doorprize/item_box_ready.svg') }}" alt="" class="w-100">
                                    <h3 class="custom-doorprize-item__title {{ $doorprize->is_drawn ? '' : 'text-white' }}">
                                        <span class="d-inline-block mb-2">{{ $doorprize->present_name }}</span> @if($doorprize->is_drawn) <br> (Done) @else <br> <span>(Ready)</span> @endif
                                    </h3>
                                @endif
                            @endif
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</div>



<script src="{{ asset('packages/jquery/jquery-3.6.1.min.js') }}"></script>
<script src="{{ asset('packages/bootstrap5/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('packages/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('packages/sweetalert@2/sweetalert2@9.js') }}"></script>
<script>
    @if(session()->has('message'))
    Swal.fire({
        icon: 'warning',
        title: '{{ session()->get('message') }}',
        text: '',
    });
    @endif

    $(document).ready(function () {
        new Swiper('.swiper-doorprizes', {
            slidesPerView: 2,
            spaceBetween: 20,

            // Navigation arrows
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },

            // And if we need scrollbar
            scrollbar: {
                el: '.swiper-scrollbar',
                draggable: true,
                dragSize: 40
            },

            breakpoints: {
                992: {
                    slidesPerView: 5,
                }
            }
        });
    });
</script>
</body>
</html>

resources/views/admin/Doorprize/generator.blade.php
@extends('crudbooster::admin_template')

@push('head')
    <style>
        .card-doorprize__item {
            color: #34395F;
        }
        .card-doorprize__name {
            background: #F5F5FB;
            border-radius: 10px;
            padding: 7px 15px;
            margin-bottom: 20px;
            color: #34395F;
        }
        .wrapper-body {
            padding: 15px;
            border-radius: 10px;
            background: #F5F5FB;
        }
        .card-doorprize__list {
            padding-bottom: 20px;
            padding-left: 40px;
            color: #34395F;
        }
        .card-doorprize__list__wrapper {
            min-height: 300px;
            overflow-x: hidden;
            padding-right: 15px;
        }
        .row-scroll {
            max-height: 804px;
            overflow-x: hidden;
        }
        .card-doorprize__list__wrapper::-webkit-scrollbar,
        .row-scroll::-webkit-scrollbar{
            width: 5px;
        }
        .card-doorprize__list__wrapper::-webkit-scrollbar-track,
        .row-scroll::-webkit-scrollbar-track {
            background: #DDCDCD;
            border-radius: 2.5px;
        }
        .card-doorprize__list__wrapper::-webkit-scrollbar-thumb,
        .row-scroll::-webkit-scrollbar-thumb {
            background: #B3ADAD;
            border-radius: 2.5px;
        }
        .card-doorprize__list__wrapper::-webkit-scrollbar-thumb:hover,
        .row-scroll::-webkit-scrollbar-thumb:hover {
            background: #999999;
        }

        .btn-generate {
            background: #00B2F9;
            border-radius: 10px;
            margin-top: 50px;
        }
    </style>
@endpush

@section('content')

    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <div class="row row-scroll">
                    @foreach($doorprizes as $doorprize)
                        <div class="col-lg-6">
                            <div class="card-doorprize mb-5">
                                <p class="card-doorprize__item mb-2">Item Name {{ $loop->iteration }}</p>

                                <h6 class="card-doorprize__name">{{ $doorprize->name }}</h6>

                                <div class="wrapper-body">
                                    <div class="card-doorprize__list__wrapper" style="max-height: 346px;min-height: 346px;">
                                        <ol class="card-doorprize__list mb-5">
                                            @foreach($doorprize->participants as $participant)
                                                <li>{{ $participant->name }}, {{ $participant->full_registration_number }}</li>
                                            @endforeach
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    </div>
{{--                    <div class="row">--}}
{{--                        <div class="col-lg-12 text-center">--}}
{{--                            <a href="{{ \crocodicstudio\crudbooster\helpers\CRUDBooster::mainpath('generate-doorprize') }}" class="btn btn-primary btn-generate">Generate Data</a>--}}
{{--                        </div>--}}
{{--                    </div>--}}
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <p class="card-doorprize__item mb-2">User Success Check-In</p>

                    <div class="wrapper-body">
                        <div class="card-doorprize__list__wrapper" style="max-height: 346px;min-height: 346px;">
                            <ol class="card-doorprize__list mb-5">
                                @foreach($participants as $participant)
                                    <li>{{ $participant->name }}, {{ $participant->full_registration_number }}</li>
                                @endforeach
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('bottom')
@endpush