routes/web.php
<?php

use App\Http\Controllers\FrontEnd\BoothController;
use App\Http\Controllers\FrontEnd\ClassroomController;
use App\Http\Controllers\FrontEnd\InvoiceController;
use App\Http\Controllers\FrontEnd\LandingController;
use App\Http\Controllers\FrontEnd\LobbyController;
use App\Http\Controllers\FrontEnd\MainStageController;
use App\Http\Controllers\FrontEnd\NotificationController;
use App\Http\Controllers\FrontEnd\ProfileController;
use App\Http\Controllers\FrontEnd\ScheduleController;
use App\Http\Middleware\CheckSession;
use App\Http\Middleware\CheckUserStatus;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'middleware' => [CheckSession::class, CheckUserStatus::class],
], function () {
    Route::get('/', [LandingController::class, 'index'])->withoutMiddleware([CheckSession::class, CheckUserStatus::class]);

    Route::post('/profile', [ProfileController::class, 'update']);

    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications', [NotificationController::class, 'update']);

    Route::get('/home', [LobbyController::class, 'home']);

    Route::get('/download-qr/{qr}', [LobbyController::class, 'downloadQr']);

    Route::get('/mainstage', [MainStageController::class, 'index']);

    Route::get('/classroom', [ClassroomController::class, 'index']);

    Route::get('/schedule-list', [ScheduleController::class, 'index']);
    Route::post('/schedule-find', [ScheduleController::class, 'show']);
    Route::post('/schedule-send-message', [ScheduleController::class, 'sendMessage']);

    Route::get('/booth', [BoothController::class, 'index']);
    Route::get('/booth-list', [BoothController::class, 'boothList']);
    Route::post('/booth-find', [BoothController::class, 'boothFind']);
    Route::get('/booth/detail', [BoothController::class, 'show']);

    Route::post('/count-visitor', function () {
        return 0;
    });

    //Invoice
    Route::get('/invoice', [InvoiceController::class, 'index']);
});

Route::get('/scannerapp', function () {
    return redirect(config('eventy.scanner_link'));
});


Route::get('/email', function () {
    $participant = \App\Models\Participant::find(64);

    $mail['event_logo'] = preferGet('logo_events');
    $mail['name'] = $participant->name;
    $mail['email'] = $participant->email;

//    $participant->sendEmailRegistration($mail);

    return view('web.Email.reminder', $mail);
});

app/Models/CmsUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class CmsUser extends Model
{
    use HasFactory;

    public const SUPERADMIN_PRIVILEGE_ID = 1;
    public const ADMIN_PRIVILEGE_ID = 2;
    public const BOOTH_PRIVILEGE_ID = 3;

    public function scanGroup()
    {
        return $this->belongsTo(ScanGroup::class);
    }

    public function getPhotoAttribute($value)
    {
        return $value ? getS3EndpointFile($value) : preferGet('icon_events');
    }

    public function boothAdmin(): HasOne
    {
        return $this->hasOne(BoothAdmin::class)->withDefault();
    }
}

app/Http/Controllers/Backoffice/BackofficeController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Helpers\Eventy;
use App\Http\Controllers\Controller;
use App\Http\Requests\EditPasswordRequest;
use App\Http\Requests\Product\Banner\CreateBannerRequest;
use App\Http\Requests\Product\Banner\EditBannerRequest;
use App\Http\Requests\Product\CreateRequest;
use App\Http\Requests\Product\UpdateRequest;
use App\Http\Requests\UploadImageRequest;
use App\Models\Booth;
use App\Models\BoothAttachment;
use App\Models\CmsUser;
use App\Repositories\BoothAdminRepository;
use App\Repositories\BoothAttachmentRepository;
use App\Repositories\BoothChatRepository;
use App\Repositories\BoothProductBannersRepository;
use App\Repositories\BoothProductEcommerceRepository;
use App\Repositories\BoothProductRepository;
use App\Repositories\BoothRepository;
use App\Repositories\BoothVisitorRepository;
use App\Repositories\CmsUsersRepository;
use App\Services\BoothAttachmentService;
use App\Services\BoothChatMessagesService;
use App\Services\BoothChatService;
use App\Services\BoothProductBannersService;
use App\Services\BoothProductEcommerceService;
use App\Traits\ApiResponser;
use crocodicstudio\crudbooster\helpers\CRUDBooster;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Facades\Excel;

class BackofficeController extends Controller
{
    use ApiResponser;

    /**
     * return get view BackOffice : index
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\View\View
     */
    public function getIndex()
    {
        $admin = CmsUser::with(['boothAdmin.booth'])->find(session('admin_id'));

        if (!$admin) CRUDBooster::redirect(CRUDBooster::adminPath(), trans('crudbooster.denied_access'));

        if ($admin->id_cms_privileges != CmsUser::BOOTH_PRIVILEGE_ID)
            CRUDBooster::redirect(CRUDBooster::adminPath(), trans('crudbooster.denied_access'));

        $data['admin'] = $admin;
        $data['booth'] = $admin->boothAdmin->booth;

        return view('admin.Backoffice.index', $data);
    }

    /**
     * get list attachment
     *
     * @param $booth_id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getListItems($booth_id): JsonResponse
    {
        try {
            $booth = Booth::with(['attachments', 'boothProducts.category'])->find($booth_id);
            $items['attachments'] = $booth->attachments;
            $items['products'] = $booth->boothProducts;

            return $this->successResponse($items);
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage(), $e->getTrace(), $e->getCode());
        }
    }

    /**
     * count total visitor
     *
     * @param $booth_id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getTotalVisitor($booth_id): JsonResponse
    {
        try {
            $response['message'] = 'success';
            $response['total'] = 0; // TODO : implement visitor

            return response()->json($response, 200);
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage(), $e->getTrace(), $e->getCode());
        }
    }

    /**
     * post upload attachment
     *
     * @throws \Exception
     */
    public function postUploadAttachment()
    {
        $type = request('type');
        $booth_attachment = new BoothAttachmentRepository();
        $booth_attachment->setBoothId(request('booth_id'));

        $total = BoothAttachmentRepository::countLimitByBoothId(request('booth_id'), $type);

        if ($total >= config('eventy.max_attachment'))
            CRUDBooster::redirectBack(sprintf('Maximum %s attachment is %u.', $type, config('eventy.max_attachment')));

        if ($type === 'video') {
            CRUDBooster::valid([
                'video_url' => 'required|string|min:1|max:255',
            ], 'session');

            $booth_attachment->setFileName(request('video_name'));
            $booth_attachment->setType('Video');
            $booth_attachment->setVideoUrl(request('video_url'));
        } else {
            if ($type === 'document') {
                CRUDBooster::valid([
                    'file' => 'required|max:2000|mimes:pdf,xls,xlsx,csv,docx,pdf,ppt,pptx',
                ], 'session');

                $file = request()->file('file');
                $filesize = $file->getSize();
                $ext = $file->getClientOriginalExtension() ?: $file->clientExtension();
                $upload = Eventy::uploadFileS3('file', '', pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME));
                $booth_attachment->setType('Document');
                $booth_attachment->setFileSize($filesize);
                $booth_attachment->setVideoUrl('');
            } else if ($type === 'image') {
                CRUDBooster::valid([
                    'image' => 'required|max:1000|mimes:jpg,jpeg,png',
                ], 'session');

                $booth_attachment->setType('Image');
                $booth_attachment->setVideoUrl('');
                $file = request()->file('image');
                $upload = Eventy::uploadFileS3('image');
            }

            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();

            $booth_attachment->setFile($upload);
            $booth_attachment->setFileName($filename);
            $booth_attachment->setExtension($extension);
        }

        $booth_attachment->save();

        CRUDBooster::redirectBack(__('eventy/backoffice.res_upload_success'), 'success');
    }

    /**
     * post delete attachment
     *
     * @param $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function postDeleteAttachment($id): JsonResponse
    {
        try {
            $find = BoothAttachmentRepository::findById($id);

            removeFileS3($find->getFile());

            $find->delete();

            $response['message'] = 'success';

            return response()->json($response, 200);
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage(), $e->getTrace(), $e->getCode());
        }
    }

    /**
     * update booth description
     *
     */
    public function postUpdateDescription()
    {
        CRUDBooster::valid([
            'description' => 'required|min:10|max:15000|string',
        ], 'session');

        $booth = BoothRepository::findById(request('booth_id'));
        $booth->setDescription(request('description'));
        $booth->save();

        CRUDBooster::redirectBack(__('eventy/backoffice.res_updated_success'), 'success');
    }

    public function postUploadSummernote()
    {
        $name = 'userfile';
        $dir = 'uploads/' . CRUDBooster::myId() . DIRECTORY_SEPARATOR . date('Y-m');
        if ($file = Eventy::uploadFileS3($name, $dir)) {
            echo Eventy::getFileS3($file);
        }
    }

    /**
     * post BackOffice : edit ecommerce
     *
     */
    public function postEcommerceEdit()
    {
        try {
            $booth_product_id = request('booth_product_id');
            $types = request('types');

            BoothProductEcommerceService::updateAllTypeByBoothProductId($types, $booth_product_id);

            CRUDBooster::redirectBack('The data has been updated !', 'success');
        } catch (Exception $e) {
            CRUDBooster::redirectBack('Failed to update data !', 'danger');
        }
    }

    /**
     * post BackOffice : move banner up
     *
     */
    public function getBannerMoveUp($id)
    {
        try {
            $banner = BoothProductBannersRepository::findById($id);

            if ($banner->getSort() == 1) {
                CRUDBooster::redirectBack('The data is already at the top of the list', 'danger');
            } else if ($banner->getSort() > 1) {

                $above = BoothProductBannersRepository::findBySortAndBoothProductId($banner->getSort() - 1, $banner->getBoothProductId()->getId());
                if ($above->getId() != '') {
                    $above->setSort($banner->getSort());
                    $above->save();
                }

                $banner->setSort($banner->getSort() - 1);
                $banner->save();
            }

            CRUDBooster::redirectBack('The data order has been changed successfully!', 'success');
        } catch (Exception $e) {
            CRUDBooster::redirectBack('Failed to move data !', 'danger');
        }
    }

    /**
     * post BackOffice : move banner down
     *
     */
    public function getBannerMoveDown($id)
    {
        try {
            $banner = BoothProductBannersRepository::findById($id);
            $bottom = BoothProductBannersRepository::findBySortAndBoothProductId($banner->getSort() + 1, $banner->getBoothProductId()->getId());

            if ($bottom->getId() == '') {
                CRUDBooster::redirectBack('The data is already at the bottom of the list', 'danger');
            } else if ($bottom->getId() != '') {
                if ($bottom->getId() != '') {
                    $bottom->setSort($banner->getSort());
                    $bottom->save();
                }

                $banner->setSort($banner->getSort() + 1);
                $banner->save();
            }

            CRUDBooster::redirectBack('The data order has been changed successfully!', 'success');
        } catch (Exception $e) {
            CRUDBooster::redirectBack('Failed to move data !', 'danger');
        }
    }

    /**
     * return get view BackOffice : detail banner
     *
     */
    public function getBannerDetail($booth_product_id = null, $id = null)
    {
        if (!$booth_product_id || !$id)
            CRUDBooster::redirect(CRUDBooster::mainpath('product'), 'Page not found !', 'danger');

        $admin = CRUDBooster::me();
        $booth = BoothAdminRepository::findBoothByCmsUsersId($admin->id);
        $row = BoothProductBannersRepository::findById($id);

resources/views/admin/Backoffice/plugin/css.blade.php
<!-- template:css -->
<link rel="stylesheet" href="{{ asset('css/font-awesome/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('packages/bootstrap5/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/admin/Backoffice/backoffice.css') . '?v=1.0.0' }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/web/Register/spinner.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/web/load.css') }}">
<!-- template:css -->

<!-- summernote codemirror -->
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">
<!-- summernote codemirror -->

<!-- plugin:css -->
<link rel="stylesheet" href="{{ asset('packages/modal-video/modal-video.min.css') }}">
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<link rel='stylesheet' href="{{ asset('crudbooster/assets/lightbox/dist/css/lightbox.min.css') }}"/>
<link rel="stylesheet" href="https://unpkg.com/placeholder-loading/dist/css/placeholder-loading.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog==" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
<!-- plugin:css -->

<link rel="shortcut icon" href="{{ asset($event_icon) }}">

<style>
    .dataTables_wrapper {
        width: 100%;
    }
</style>

resources/views/admin/Backoffice/plugin/js.blade.php
<script>
    url_base = '{{ url('/') }}';
    token = '{{ csrf_token() }}';
    event_channel = '{{ config("eventy.event_channel") }}';
    timezone_events = '{{ preferGet("timezone_events") }}';
    zoomUrl = '{{ url("zoom-meet") }}/';
    youtubeUrl = 'https://www.youtube.com/embed/';
    is_mobile = '';
    debug = '{{ config("app.debug") }}';
    ipAddress = "{{ request()->ip() }}";
    path = "{{ request()->path() }}";
    breakpoints = {
        sm: 576,
        md: 768,
        lg: 992,
        xlg: 1200,
    };
</script>
<!-- template:js -->
<script src="{{ asset('packages/jquery/jquery-3.6.1.min.js') }}"></script>
<!-- template:js -->

<!-- summernote codemirror -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js"></script>
<!-- summernote codemirror -->

<!-- plugin:js -->
<script src="{{ asset('packages/bootstrap5/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('packages/modal-video/modal-video.js') }}"></script>
<script src="{{ asset('crudbooster/assets/summernote/summernote-bs4.min.js') }}"></script>
<script src="{{ asset('packages/sweetalert@2/sweetalert2@9.js') }}"></script>
<script src="{{ asset('crudbooster/assets/lightbox/dist/js/lightbox.min.js') }}"></script>
<script src="{{ asset('packages/axios/axios.min.js') }}"></script>
@if(config('app.debug'))
    <script src="{{ asset('packages/vue@2/vue.js') }}"></script>
@else
    <script src="{{ asset('packages/vue@2/vue.min.js') }}"></script>
@endif
<script src="{{ asset('packages/dayjs/dayjs-1.11.4.min.js') }}"></script>
<script src="{{ asset('js/web/Template/load.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous"></script>
<script src="{{ asset('crudbooster/jquery.price_format.2.0.min.js') }}"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
<!-- plugin:js -->

<script src="{{ asset(mix('js/laravel-echo-setup.js')) }}"></script>
<script>
function urlify(text) {
    return text.replace(/(https?:\/\/[^\s]+)/g, function(url) {
        return '<a href="' + url + '" target="_blank">' + url + '</a>';
    });
}

function strip_tags(text) {
    return text.replace(/<[^>]+>/g, '');
}

summernoteUploadUrl = '{{ url('upload-summernote') }}';

toast = Swal.mixin({
    toast: true,
    position: 'top',
    showConfirmButton: false,
    timer: 4000,
    timerProgressBar: true,
    onOpen: (toast) => {
        toast.addEventListener('mouseenter', Swal.stopTimer);
        toast.addEventListener('mouseleave', Swal.resumeTimer);
    }
});

axios = axios.create({
    baseURL: url_base + '/backoffice',
    headers: {
        'X-CSRF-TOKEN': token,
        'X-Requested-With': 'XMLHttpRequest'
    }
});

axios.interceptors.request.use((config) => {
    config.headers['X-Socket-ID'] = window.Echo.socketId() // Echo instance
    return config;
});

axios.interceptors.response.use(function (response) {
    return response;
}, function (error) {
    let status = error.response.status.toString();
    if (status === '419') {
        window.location.reload();
    }

    $('#preloader-active').delay(450).fadeOut('slow');
    if (error.response && !status.startsWith('5')) {
        toast.fire({
            icon: 'error',
            title: error.response.data.message,
        });
    } else {
        toast.fire({
            icon: 'error',
            title: error.message,
        });
    }

    return Promise.reject(error);
});

Vue.prototype.$http = axios;
Vue.prototype.$toast = toast;
Vue.prototype.$swal = Swal;
let EventBus = new Vue();
</script>
<script>
    $(document).on('click', '#btn-edit-pass', function() {
        $('#side-profil').hide();
        $('#side-password').show(450);
    });

    let admin = {
        id: '{{ $admin->id }}',
        name: '{{ $admin->name }}',
        image: '{{ $admin->photo }}',
        email: '{{ $admin->email }}',
    };

    let booth = {
        id: '{{ $booth->id }}',
        name: '{{ $booth->name }}',
    };
</script>
<script>
    function showPassword(button) {
        var inputPassword = $(button).parent().find('input');
        if (inputPassword.attr('type') === 'password') {
            inputPassword.attr('type', 'text');
        } else {
            inputPassword.attr('type','password');
        }
    }

    $(document).ready(function() {
        $('.show-password').on('click', function(){
            showPassword(this);
        });

        $('#dataTable').DataTable({
            'ordering': false
        });

        $("#dataTable .checkbox").click(function () {
            var is_any_checked = $("#dataTable .checkbox:checked").length;
            if (is_any_checked) {
                $(".btn-delete-selected").removeClass("disabled");
            } else {
                $(".btn-delete-selected").addClass("disabled");
            }
        });

        $("#dataTable #checkall").click(function () {
            var is_checked = $(this).is(":checked");
            $("#dataTable .checkbox").prop("checked", !is_checked).trigger("click");
        });

        $('.btn-action-deleted').click(function () {
            Swal.fire({
                title: 'Are you sure ?',
                text: 'You will not be able to recover this record data!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#form-table').submit();
                }
            });
        });

        $('.inputMoney').priceFormat({
            'prefix': '',
            'thousandsSeparator': ',',
            'centsLimit': '0',
            'clearOnEmpty': false
        });

        let dropify = $('.dropify').dropify();
        dropify.on('dropify.beforeClear', function(event, element){
            return confirm('Are you sure to delete ?');
        });

        dropify.on('dropify.afterClear', function(event, element){
            let deleteUrl = element.element.dataset.deleteUrl;
            axios.get(deleteUrl)
                .then(() => {
                    console.log('success');
                })
                .catch(() => {
                    swal('Failed to delete image!', '', 'error');
                });
        });
    });
</script>
<script src="{{ asset('js/admin/Backoffice/header.js') . '?v=1.0.0' }}"></script>
<script src="{{ asset('js/admin/Backoffice/profile.js') . '?v=1.0.0' }}"></script>
<script src="{{ asset('js/admin/Backoffice/index.js') . '?v=1.0.0' }}"></script>
<script src="{{ asset('js/admin/Backoffice/summernote.js') }}"></script>
<script src="{{ asset('js/admin/Backoffice/jquery-attachment.js') }}"></script>